# Generated by Django 6.0 on 2026-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeaddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={},
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=50),
        ),
    ]
