# Generated by Django 6.0 on 2026-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
